// <auto-generated />
using System;
using ForumManagmentSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumManagmentSystem.Infrastructure.Migrations
{
    [DbContext(typeof(FMSContext))]
    [Migration("20240118120837_UsersSeeding")]
    partial class UsersSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostLikesDb", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostTagsDb", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.ReplyDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.ReplyLikesDb", b =>
                {
                    b.Property<Guid>("ReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReplyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ReplyLikes");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.TagDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa809d98-011f-4a99-bc16-f3ed28a11087"),
                            IsDeleted = false,
                            Name = "funny"
                        },
                        new
                        {
                            Id = new Guid("3821394b-e2d1-4c76-9794-5b1ced0167ac"),
                            IsDeleted = false,
                            Name = "event"
                        },
                        new
                        {
                            Id = new Guid("d2cf4e8f-d6e5-4896-bb28-f085c19cd2fb"),
                            IsDeleted = false,
                            Name = "charity"
                        },
                        new
                        {
                            Id = new Guid("f1515d9b-447a-4272-ab46-8b60e98635dc"),
                            IsDeleted = false,
                            Name = "tournament"
                        },
                        new
                        {
                            Id = new Guid("5c291373-f99c-46dc-ad5b-cf65dab10e4a"),
                            IsDeleted = false,
                            Name = "science"
                        },
                        new
                        {
                            Id = new Guid("c2a2243e-41e6-4709-be4b-0b13bc90304f"),
                            IsDeleted = false,
                            Name = "economy"
                        },
                        new
                        {
                            Id = new Guid("d06b7c90-3f47-4863-8fbd-0dccdff99a82"),
                            IsDeleted = false,
                            Name = "investment"
                        },
                        new
                        {
                            Id = new Guid("633b87a9-07de-4b61-a299-26772df39620"),
                            IsDeleted = false,
                            Name = "Sofiq"
                        },
                        new
                        {
                            Id = new Guid("15c2084c-0066-4066-88c1-6a04cb5f3fdb"),
                            IsDeleted = false,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = new Guid("f65fd854-b94e-4a33-908a-1a16047810bb"),
                            IsDeleted = false,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = new Guid("fb71c371-18a4-4282-b830-4822ba3a423f"),
                            IsDeleted = false,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = new Guid("27083416-5d6f-424c-bdc8-28d403db5319"),
                            IsDeleted = false,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("70821498-d479-4abd-85d0-272aaca771a1"),
                            IsDeleted = false,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = new Guid("47ccafb1-ad6f-4ee8-b887-70b750f8b5c3"),
                            IsDeleted = false,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = new Guid("ca7db341-5a3d-4ae0-9267-badfbf38fdc8"),
                            IsDeleted = false,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = new Guid("985e2478-e0f8-4c19-9584-36582a768c88"),
                            IsDeleted = false,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("e01a3224-4aa9-4078-9d10-d1f766012533"),
                            IsDeleted = false,
                            Name = "North America"
                        },
                        new
                        {
                            Id = new Guid("a96d1c49-c671-4eda-9631-bf7391bb7a77"),
                            IsDeleted = false,
                            Name = "South America"
                        });
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e806ad30-83cb-4bbe-a350-ae52c1f9bf73"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test1@mail.com",
                            FirstName = "test1A",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "test1B",
                            PasswordHash = new byte[] { 176, 106, 231, 100, 108, 29, 115, 161, 14, 148, 23, 30, 182, 158, 247, 123, 201, 10, 65, 203, 194, 13, 241, 178, 112, 17, 20, 234, 84, 22, 78, 173, 189, 179, 19, 170, 218, 107, 94, 188, 99, 222, 178, 144, 2, 42, 112, 59, 65, 153, 167, 161, 78, 38, 210, 238, 154, 190, 85, 226, 161, 100, 131, 44 },
                            PasswordSalt = new byte[] { 150, 226, 213, 246, 103, 226, 64, 200, 233, 86, 209, 89, 127, 33, 123, 161, 86, 253, 227, 236, 3, 195, 5, 152, 141, 197, 135, 78, 163, 232, 142, 18, 176, 185, 243, 46, 84, 25, 48, 214, 189, 77, 151, 95, 147, 42, 252, 161, 140, 194, 214, 25, 230, 195, 31, 64, 118, 183, 152, 35, 184, 220, 74, 149, 152, 189, 63, 46, 242, 6, 17, 6, 64, 131, 216, 114, 72, 190, 152, 177, 86, 252, 181, 188, 124, 222, 122, 42, 246, 207, 55, 245, 55, 3, 73, 124, 232, 200, 251, 167, 80, 86, 27, 153, 181, 58, 182, 90, 169, 111, 211, 212, 61, 62, 107, 5, 180, 87, 46, 178, 247, 9, 31, 78, 200, 19, 177, 87 },
                            Username = "test1"
                        },
                        new
                        {
                            Id = new Guid("3522894c-0f15-4f9e-b379-ab644f4e918e"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tes2@mail.com",
                            FirstName = "test2A",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "test2B",
                            PasswordHash = new byte[] { 165, 196, 217, 130, 173, 225, 82, 58, 64, 96, 126, 243, 81, 198, 152, 7, 239, 105, 101, 244, 37, 212, 243, 220, 45, 85, 136, 31, 149, 218, 147, 156, 131, 200, 141, 191, 78, 163, 10, 102, 213, 167, 132, 32, 206, 143, 91, 103, 230, 176, 97, 52, 252, 232, 236, 1, 65, 228, 140, 96, 110, 48, 245, 29 },
                            PasswordSalt = new byte[] { 46, 78, 60, 63, 212, 204, 100, 222, 52, 81, 27, 53, 207, 179, 178, 138, 219, 242, 62, 101, 24, 50, 134, 14, 117, 221, 2, 114, 111, 25, 175, 186, 206, 226, 115, 203, 226, 10, 53, 14, 241, 202, 163, 43, 96, 133, 235, 93, 215, 212, 143, 247, 105, 99, 1, 145, 96, 198, 180, 196, 126, 64, 8, 4, 150, 174, 191, 71, 205, 138, 116, 193, 165, 49, 105, 68, 111, 39, 88, 245, 170, 2, 150, 45, 73, 138, 28, 66, 16, 164, 138, 11, 221, 108, 165, 25, 80, 155, 194, 139, 119, 215, 151, 108, 156, 129, 22, 73, 208, 61, 109, 153, 123, 38, 127, 84, 221, 42, 210, 93, 103, 20, 45, 251, 219, 80, 90, 12 },
                            Username = "test2"
                        },
                        new
                        {
                            Id = new Guid("b87b9540-c07f-4ce6-905d-41e2f33a6a95"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@mail.com",
                            FirstName = "admin1A",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "admin1B",
                            PasswordHash = new byte[] { 100, 174, 69, 49, 244, 40, 75, 242, 75, 190, 7, 50, 191, 21, 210, 51, 175, 89, 167, 216, 73, 209, 117, 127, 139, 6, 180, 213, 120, 123, 133, 100, 188, 7, 2, 113, 119, 171, 30, 108, 70, 31, 89, 21, 19, 74, 54, 168, 215, 248, 61, 25, 88, 232, 12, 142, 33, 133, 48, 181, 98, 99, 28, 12 },
                            PasswordSalt = new byte[] { 43, 56, 56, 111, 186, 118, 3, 172, 167, 56, 181, 194, 18, 120, 38, 44, 137, 72, 218, 163, 59, 187, 112, 33, 97, 84, 98, 154, 97, 235, 245, 32, 84, 45, 125, 196, 21, 83, 244, 137, 213, 139, 121, 57, 94, 1, 246, 221, 12, 23, 215, 214, 55, 71, 95, 63, 80, 125, 227, 215, 222, 181, 230, 236, 115, 100, 176, 93, 123, 253, 250, 164, 139, 9, 44, 103, 183, 94, 206, 158, 143, 89, 195, 79, 216, 67, 113, 158, 40, 113, 128, 113, 134, 82, 255, 141, 63, 144, 198, 189, 93, 213, 143, 48, 75, 0, 205, 196, 250, 159, 165, 251, 43, 148, 33, 154, 107, 114, 204, 180, 14, 17, 75, 195, 74, 155, 208, 6 },
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", b =>
                {
                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", "User")
                        .WithMany("MyPosts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostLikesDb", b =>
                {
                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", "User")
                        .WithMany("LikedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostTagsDb", b =>
                {
                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.TagDb", "Tag")
                        .WithMany("Posts")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.ReplyDb", b =>
                {
                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", "User")
                        .WithMany("MyReplies")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.ReplyLikesDb", b =>
                {
                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.ReplyDb", "Reply")
                        .WithMany("Likes")
                        .HasForeignKey("ReplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", "User")
                        .WithMany("MyLikedReplies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.PostDb", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.ReplyDb", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.TagDb", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumManagmentSystem.Infrastructure.Data.Models.UserDb", b =>
                {
                    b.Navigation("LikedPosts");

                    b.Navigation("MyLikedReplies");

                    b.Navigation("MyPosts");

                    b.Navigation("MyReplies");
                });
#pragma warning restore 612, 618
        }
    }
}
